<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>CtrlCleaner</AssemblyName>
    <RootNamespace>CtrlCleaner</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <!-- mp4 embedded — extracted to temp at runtime -->
    <EmbeddedResource Include="Assets\ctrl_1.mp4"/>
    <!-- Fonte Minecraft embutida como Resource WPF -->
    <Resource Include="Fonts\Minecraft.ttf"/>
  </ItemGroup>

</Project>
